import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';
import aspectRatio from '@tailwindcss/aspect-ratio';
const config: Config = {
  darkMode: 'class', // Explicitly set to 'class' for next-themes compatibility
  content: [
    './src/app/**/*.{ts,tsx}', // All App Router files
    './src/components/**/*.{ts,tsx}', // All components
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        primary: { // Straw: #d7b990
          '50': '#ffffff',
          '100': '#faf7f2',
          '200': '#f1e7da',
          '300': '#e8d8c1',
          '400': '#dfc8a8',
          '500': '#d7b990',
          '600': '#a78f70',
          '700': '#776650',
          '800': '#473d30',
          '900': '#171410',
          '950': '#000000',
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: { // Spring Wood: #f7f3ed
          '50': '#ffffff',
          '100': '#fefdfd',
          '200': '#fcfbf9',
          '300': '#faf8f5',
          '400': '#f8f5f1',
          '500': '#f7f3ed',
          '600': '#c0bdb8',
          '700': '#898783',
          '800': '#52514f',
          '900': '#1b1b1a',
          '950': '#000000',
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        accent: { // Taupe: #524239
          '50': '#ffffff',
          '100': '#ebeae9',
          '200': '#c5c0bd',
          '300': '#9e9691',
          '400': '#786c65',
          '500': '#524239',
          '600': '#3f332c',
          '700': '#2d241f',
          '800': '#1b1613',
          '900': '#090706',
          '950': '#000000',
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        muted: { // Tapa: #776f6b
          '50': '#ffffff',
          '100': '#efefee',
          '200': '#d1cfcd',
          '300': '#b3afac',
          '400': '#958f8b',
          '500': '#776f6b',
          '600': '#5c5653',
          '700': '#423d3b',
          '800': '#272523',
          '900': '#0d0c0b',
          '950': '#000000',
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        neutral: { // Complementary neutral tone
          '50': '#f9fafb',
          '100': '#f1f2f3',
          '200': '#e5e7eb',
          '300': '#d1d5db',
          '400': '#9ca3af',
          '500': '#6b7280',
          '600': '#4b5563',
          '700': '#374151',
          '800': '#1f2937',
          '900': '#111827',
          '950': '#0a0f1a',
          DEFAULT: 'hsl(var(--neutral))',
          foreground: 'hsl(var(--neutral-foreground))',
        },
        highlight: { // Warm accent for emphasis
          '50': '#fff7e6',
          '100': '#ffedcc',
          '200': '#ffdb99',
          '300': '#ffca66',
          '400': '#ffb833',
          '500': '#f5a623',
          '600': '#d98c1d',
          '700': '#b37318',
          '800': '#8c5913',
          '900': '#66400e',
          '950': '#402809',
          DEFAULT: 'hsl(var(--highlight))',
          foreground: 'hsl(var(--highlight-foreground))',
        },
        base: { // Soft background tone
          '50': '#fffefa',
          '100': '#fefcf5',
          '200': '#fdf9eb',
          '300': '#fbf5e1',
          '400': '#faf2d7',
          '500': '#f8eed0',
          '600': '#e0d6b8',
          '700': '#c8bea0',
          '800': '#b0a688',
          '900': '#988e70',
          '950': '#807658',
          DEFAULT: 'hsl(var(--base))',
          foreground: 'hsl(var(--base-foreground))',
        },
        contrast: { // Deep contrast for dark elements
          '50': '#e6e9ee',
          '100': '#ccd3dc',
          '200': '#99a7ba',
          '300': '#667b97',
          '400': '#335075',
          '500': '#0f263e',
          '600': '#0c1f33',
          '700': '#091828',
          '800': '#06121e',
          '900': '#030c14',
          '950': '#02080d',
          DEFAULT: 'hsl(var(--contrast))',
          foreground: 'hsl(var(--contrast-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'admin-primary': 'var(--admin-primary)',
        'admin-foreground': 'var(--admin-foreground)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'zoom-in': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'zoom-in': 'zoomIn 0.2s ease-out',
      },
      fontFamily: {
        arabic: ['Cairo', 'Noto Sans Arabic', 'sans-serif'],
        english: ['Inter', 'Roboto', 'sans-serif'],
      },
    },
  },
  plugins: [animate, forms, typography, aspectRatio],
};
export default config;